// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Domain_WidgetCode$Reason = require("./Domain/Domain_WidgetCode.bs.js");

var c = Domain_WidgetCode$Reason.create("wat");

var WidgetCode = 0;

var UnitQuantity = 0;

exports.WidgetCode   = WidgetCode;
exports.UnitQuantity = UnitQuantity;
exports.c            = c;
/* c Not a pure module */
