// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Domain_WidgetCode$Reason = require("./Domain/Domain_WidgetCode.bs.js");

var g = Domain_WidgetCode$Reason.create("yay");

exports.g = g;
/* g Not a pure module */
