// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block        = require("bs-platform/lib/js/block.js");
var Js_option    = require("bs-platform/lib/js/js_option.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function create(code) {
  var isMatch = Js_option.isSome(Js_primitive.null_to_opt(new RegExp("W\\d{4}").exec(code)));
  if (isMatch) {
    return /* Ok */Block.__(0, [/* WidgetCode */[code]]);
  } else {
    return /* Error */Block.__(1, ["`WidgetCode` must begin with a 'W' and be followed by 4 digits"]);
  }
}

function value(param) {
  return param[0];
}

exports.create = create;
exports.value  = value;
/* No side effect */
