// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function create(qty) {
  if (qty < 1) {
    return /* Error */Block.__(1, ["`UnitQuantity` cannot be less than 1"]);
  } else if (qty > 1000) {
    return /* Error */Block.__(1, ["`UnitQuantity` cannot be greater than 1000"]);
  } else {
    return /* Ok */Block.__(0, [/* UnitQuantity */[qty]]);
  }
}

function value(param) {
  return param[0];
}

exports.create = create;
exports.value  = value;
/* No side effect */
